sudo: required

language: python

services:
  - docker

env:
  - PIPENV_VENV_IN_PROJECT=1 PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - sudo apt-get install thrift-compiler
  - make thrift

install:
  - pip install pipenv
  - pipenv --three
  - pipenv install --dev
  - pipenv install 

script:
  - pipenv run pytest -s -v

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

  - docker build -t kafka-consumer -f consumer/Dockerfile ./consumer
  - docker tag kafka-consumer artlitvinov/kafka-consumer:latest
  - docker push artlitvinov/kafka-consumer:latest

  - docker build -t kafka-webserver -f webserver/Dockerfile ./webserver
  - docker tag kafka-webserver artlitvinov/kafka-webserver:latest
  - docker push artlitvinov/kafka-webserver:latest

  - docker build -t cassandra-prepare -f cassandra_prepare/Dockerfile ./cassandra_prepare
  - docker tag cassandra-prepare artlitvinov/cassandra-prepare:latest
  - docker push artlitvinov/cassandra-prepare:latest
