version: '3'
services:
  web:
    image: webserver
    build: ./webserver
    restart: on-failure
    environment:
      - WEBSERVER_PORT=5000
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra
    ports:
      - "5000:5000"

  consumer:
    image: consumer
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra
    deploy:
      mode: replicated
      replicas: 3

  cassandra:
    image: "cassandra:latest"
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 1G
    deploy:
      resources:
        limits:
          memory: 2G
