version: '3'
services:
  web:
    image: "artlitvinov/akvelon:kafka_webserver"
    depends_on:
      - cassandra
    ports:
      - "5000:5000"
    networks:
      - backend
  
  consumer:
    image: "artlitvinov/akvelon:kafka_consumer"
    depends_on:
      - cassandra
    networks:
      - backend
  
  cassandra:
    image: "artlitvinov/akvelon:kafka_cassandra"
    networks:
      - backend
networks:
  backend: