version: '3'
services:
  web:
    image: webserver
    build: ./webserver
    restart: on-failure
    environment:
      - WEBSERVER_PORT=5000
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra
    ports:
      - "5000:5000"

  consumer1:
    image: consumer1
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra

  consumer2:
    image: consumer2
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra

  consumer3:
    image: consumer3
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=172.20.0.2
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra

  cassandra_prepare:
    image: cassandra_prepare
    build: ./cassandra_prepare
    restart: on-failure
    environment:
      - CASSANDRA_HOST=172.20.0.2
    depends_on:
      - cassandra

  cassandra:
    image: 'cassandra'
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 1G
      CASSANDRA_LISTEN_ADDRESS: 172.20.0.2
    deploy:
      resources:
        limits:
          memory: 2G

  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'

  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'

  cadvisor:
    image: 'google/cadvisor:latest'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '8080:8080'
