version: '3'
services:
  web:
    image: webserver
    build: ./webserver
    restart: on-failure
    environment:
      - WEBSERVER_PORT=5000
      - CASSANDRA_HOST=127.0.0.1
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra
    ports:
      - "5000:5000"

  consumer:
    image: consumer
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=127.0.0.1
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra

  cassandra:
    image: "cassandra:latest"
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
