version: '3'
services:
  web:
    image: webserver
    build: ./webserver
    restart: always
    network_mode: bridge
    environment:
      - WEBSERVER_PORT=5000
      - CASSANDRA_HOST=cassandra
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra
    ports:
      - "5000:5000"
      - "8000:8000"

  consumer:
    build: ./consumer
    restart: on-failure
    environment:
      - CASSANDRA_HOST=cassandra
      - KAFKA_HOST=34.214.200.68
    depends_on:
      - cassandra

  cassandra_prepare:
    build: ./cassandra_prepare
    restart: on-failure
    command: ./wait-for cassandra:9042 --
      cqlsh cassandra --cqlversion="3.4.4" -f prepare.cql
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      - cassandra

  cassandra:
    image: 'cassandra'
    environment:
      MAX_HEAP_SIZE: 2G
      HEAP_NEWSIZE: 1G
    deploy:
      resources:
        limits:
          memory: 2G
